name: Create New Project

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Nazwa nowego repozytorium"
        required: true
        default: "my-new-repo"

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Konfiguracja użytkownika Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Weryfikacja użytkownika
        run: |
          ALLOWED_USER="aleksanderjedynak"
          if [ "${{ github.actor }}" != "$ALLOWED_USER" ]; then
            echo "Error: Workflow może być uruchamiany tylko przez $ALLOWED_USER."
            exit 1
          fi

      - name: Sprawdzenie uprawnień PERSONAL_ACCESS_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          response=$(curl -o /dev/null -s -w "%{http_code}" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/)
          if [ "$response" -ne 200 ]; then
            echo "Error: Nie można uwierzytelnić za pomocą PERSONAL_ACCESS_TOKEN."
            exit 1
          fi

      - name: Konfiguracja uwierzytelnienia Gita
        run: |
          git config --global url."https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Walidacja nazwy repozytorium
        run: |
          REPO_NAME="${{ github.event.inputs.repo_name }}"
          if ! [[ "$REPO_NAME" =~ ^[a-zA-Z0-9_-]+$ ]]; then
            echo "Error: Nazwa repozytorium może zawierać tylko litery, cyfry, myślniki i podkreślenia."
            exit 1
          fi
          echo "Nazwa repozytorium '$REPO_NAME' jest poprawna."

      - name: Klonowanie bazowego repozytorium
        run: |
          REPO_NAME="${{ github.event.inputs.repo_name }}"
          git clone https://github.com/${{ github.actor }}/basic.git "$REPO_NAME" || {
            echo "Error: Nie udało się sklonować bazowego repozytorium."
            exit 1
          }
          cd "$REPO_NAME"

          # Usuń stare repozytorium Git
          rm -rf .git
          rm -rf README.md
          git init

          # Ustawienie wersji na 0.0.0 w package.json (jeśli istnieje)
          if [ -f package.json ]; then
            jq '.version = "0.0.0"' package.json > temp.json && mv temp.json package.json
          fi

          # Dodanie wszystkich zmian do repozytorium
          git add .
          git commit -m "Initial commit with version 0.0.0 from basic repository by ${{ github.actor }}"

      - name: Tworzenie repozytorium na GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          REPO_NAME="${{ github.event.inputs.repo_name }}"
          response=$(curl -s -o response.json -w "%{http_code}" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"name\":\"$REPO_NAME\"}" \
            https://api.github.com/user/repos)
          if [ "$response" -ne 201 ]; then
            echo "Error: Nie udało się utworzyć repozytorium na GitHub. Szczegóły:"
            echo "Status odpowiedzi: $response"
            echo "Szczegóły błędu:"
            cat response.json
            exit 1
          else
            echo "Repozytorium '$REPO_NAME' zostało pomyślnie utworzone."
          fi

      - name: Push do nowego repozytorium
        run: |
          REPO_NAME="${{ github.event.inputs.repo_name }}"
          cd "$REPO_NAME"
          git remote add origin https://github.com/${{ github.actor }}/"$REPO_NAME".git
          git branch -M main
          git push -u origin main

      - name: Połączenie repozytorium z Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          REPO_NAME="${{ github.event.inputs.repo_name }}"
          OWNER="${{ github.actor }}"
          API_RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
            -X POST https://api.vercel.com/v9/projects \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "'"$REPO_NAME"'",
              "gitRepository": {
                "type": "github",
                "repo": "'"$OWNER/$REPO_NAME"'"
              }
            }')

          if [ "$API_RESPONSE" -ne 200 ]; then
            echo "Error: Nie udało się połączyć repozytorium z Vercel. Szczegóły:"
            cat response.json
            exit 1
          else
            echo "Repozytorium zostało pomyślnie połączone z Vercel."
          fi

      - name: Jednorazowe wdrożenie na Vercel
        run: |
          cd "${{ github.event.inputs.repo_name }}"
          npm install -g vercel
          vercel deploy --prod --yes --token "${{ secrets.VERCEL_TOKEN }}"

      - name: Timeout po wdrożeniu na Vercel
        run: |
          echo "Oczekiwanie 1 minuty, aby upewnić się, że strona jest dostępna..."
          sleep 60

      - name: Sprawdzenie dostępności strony
        run: |
          DEPLOY_URL="https://${{ github.event.inputs.repo_name }}.vercel.app"
          echo "Sprawdzanie dostępności strony pod adresem: $DEPLOY_URL"
          HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" $DEPLOY_URL)
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Strona nie jest dostępna (status: $HTTP_STATUS). Miniatura nie zostanie wygenerowana."
            exit 0
          fi
          echo "Strona jest dostępna. Kontynuuję generowanie miniatury."

      - name: Generowanie miniatury
        env:
          PAGESPEED_API_KEY: ${{ secrets.PAGESPEED_API_KEY }}
        run: |
          DEPLOY_URL="https://${{ github.event.inputs.repo_name }}.vercel.app"
          API_URL="https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=$DEPLOY_URL&key=$PAGESPEED_API_KEY"

          echo "Rozpoczynam generowanie miniatury dla: $DEPLOY_URL"
          RESPONSE=$(curl -s "$API_URL")
          
          # Debugowanie odpowiedzi
          echo "Pełna odpowiedź API Google PageSpeed Insights:"
          echo "$RESPONSE" | jq .

          # Wyciągnięcie pierwszej miniatury z 'screenshot-thumbnails'
          THUMBNAIL=$(echo "$RESPONSE" | jq -r '.lighthouseResult.audits["screenshot-thumbnails"].details.items[0].data // empty')

          # Sprawdzenie, czy dane miniatury są dostępne
          if [ -z "$THUMBNAIL" ]; then
            echo "Error: API Google PageSpeed Insights nie zwróciło danych miniatury w screenshot-thumbnails."
            exit 0
          fi

          # Próba zapisania miniatury
          echo "$THUMBNAIL" | base64 -d > thumbnail.jpg || {
            echo "Error: Nie udało się zapisać miniatury. Sprawdź dane zwrócone przez API."
            exit 1
          }
          echo "Miniatura została wygenerowana i zapisana jako thumbnail.jpg."



      - name: Wypychanie miniatury do repozytorium
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add thumbnail.png || {
            echo "Error: Nie udało się dodać miniatury do indeksu Git."
            exit 1
          }
          git commit -m "Dodanie miniatury projektu" || {
            echo "Error: Nie udało się zatwierdzić zmian w Git."
            exit 1
          }
          git push origin main || {
            echo "Error: Nie udało się wypchnąć zmian do repozytorium."
            exit 1
          }
          echo "Miniatura została pomyślnie wypchnięta do repozytorium."
