name: Deploy to Vercel and Generate Thumbnail

on:
  repository_dispatch:
    types:
      - start-deploy-and-thumbnail

jobs:
  deploy-to-vercel:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie kodu źródłowego
        uses: actions/checkout@v3

      - name: Konfiguracja Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Debugowanie sekretów
        run: |
          echo "VERCEL_TOKEN: ${VERCEL_TOKEN:+OK}"
          echo "PAGESPEED_API_KEY: ${PAGESPEED_API_KEY:+OK}"
          echo "PERSONAL_ACCESS_TOKEN: ${PERSONAL_ACCESS_TOKEN:+OK}"

      - name: Instalacja Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalacja CLI Vercel
        run: |
          npm install -g vercel

      - name: Wdrożenie na Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel deploy --prod --yes --token $VERCEL_TOKEN

      - name: Generowanie miniatury
        env:
          PAGESPEED_API_KEY: ${{ secrets.PAGESPEED_API_KEY }}
        run: |
          deployUrl="https://${{ github.repository }}.vercel.app"
          apiUrl="https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=$deployUrl&key=$PAGESPEED_API_KEY"
          thumbnail=$(curl -s $apiUrl | jq -r '.lighthouseResult.audits["final-screenshot"].details.data')
          echo "$thumbnail" | base64 -d > thumbnail.png

      - name: Commit i push miniatury
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add thumbnail.png
          git commit -m "Dodanie miniatury"
          git push
