name: Generate Thumbnail

on:
  push:
    branches:
      - main

jobs:
  generate-thumbnail:
    runs-on: ubuntu-latest

    steps:
      # 1. Sprawdzenie, czy repozytorium jest połączone z Vercel
      - name: Sprawdzenie połączenia z Vercel
        id: check-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          REPO_NAME=$(basename -s .git `git config --get remote.origin.url`)
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
            -X GET "https://api.vercel.com/v9/projects/$REPO_NAME" \
            -H "Authorization: Bearer $VERCEL_TOKEN")

          if [ "$RESPONSE" -ne 200 ]; then
            echo "Projekt '$REPO_NAME' nie jest połączony z Vercel. Nic do robienia."
            echo "::set-output name=proceed::false"
          else
            echo "Projekt '$REPO_NAME' jest połączony z Vercel. Kontynuuję workflow."
            echo "::set-output name=proceed::true"
          fi

      # 2. Generowanie miniatury (tylko jeśli połączenie z Vercel istnieje)
      - name: Generowanie miniatury
        if: steps.check-vercel.outputs.proceed == 'true'
        env:
          PAGESPEED_API_KEY: ${{ secrets.PAGESPEED_API_KEY }}
        run: |
          REPO_NAME=$(basename -s .git `git config --get remote.origin.url`)
          DEPLOY_URL="https://${REPO_NAME}.vercel.app"
          API_URL="https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=$DEPLOY_URL&key=$PAGESPEED_API_KEY"

          echo "Rozpoczynam generowanie miniatury dla: $DEPLOY_URL"
          THUMBNAIL=$(curl -s "$API_URL" | jq -r '.lighthouseResult.audits["final-screenshot"].details.data') || {
            echo "Error: Nie udało się pobrać miniatury z PageSpeed Insights."
            exit 1
          }
          if [[ $THUMBNAIL != null ]]; then
            echo "$THUMBNAIL" | base64 -d > thumbnail.png || {
              echo "Error: Nie udało się zapisać miniatury."
              exit 1
            }
            echo "Miniatura została wygenerowana i zapisana jako thumbnail.png."
          else
            echo "Error: PageSpeed Insights nie zwrócił danych miniatury."
            exit 1
          fi

      # 3. Wypychanie miniatury do repozytorium (tylko jeśli połączenie z Vercel istnieje)
      - name: Wypychanie miniatury do repozytorium
        if: steps.check-vercel.outputs.proceed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add thumbnail.png || {
            echo "Error: Nie udało się dodać miniatury do indeksu Git."
            exit 1
          }
          git commit -m "Dodanie miniatury projektu" || {
            echo "Error: Nie udało się zatwierdzić zmian w Git."
            exit 1
          }
          git push origin main || {
            echo "Error: Nie udało się wypchnąć zmian do repozytorium."
            exit 1
          }
          echo "Miniatura została pomyślnie wypchnięta do repozytorium."
